language: php
php:
  - 7.2
  - 7.4

before_script:
  - composer self-update
  - composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --no-suggest

script:
  - vendor/bin/phpcs --ignore=/.git/,/vendor/ --standard=vendor/glpi-project/coding-standard/GlpiStandard/ -n ./

cache:
  directories:
    - $HOME/.composer/cache
