language: php

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install -o
#  - mysql -u root -e 'create database glpitest;'
#  - php tools/cliinstall.php --lang=en_US --db=glpitest --user=root --tests
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
#  - mysql -u root -e 'select version();'
#  - phpunit --verbose
  - phpcs -p --ignore=vendor --standard=tools/phpcs-rules.xml  .

matrix:
  include:
    - php: 5.4
      addons:
        mariadb: 5.5
    - php: 5.5
      addons:
        mariadb: 5.5
    - php: 5.6
      addons:
        mariadb: 5.5
    - php: 5.6
      addons:
        mariadb: 10.0
    - php: 5.6
      addons:
        mariadb: 10.1
    - php: 7.0
      addons:
        mariadb: 10.0
    - php: 7.0
      addons:
        mariadb: 10.1
    - php: nightly
      addons:
        mariadb: 10.1
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#channel"
#    on_success: change
#    on_failure: always
#    use_notice: true
#    skip_join: true
